#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 1) Faça um programa que receba a idade do
# usuário e imprima se ele é maior de idade ou não.

idade=int(input("Digite sua idade: "))
if idade>=18:
    print("Você é maior de idade.")
else:
    print("Você é menor de idade.")
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")