#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 2) Faça um programa que peça ao usuário para 
# digitar um número e informe se é par ou ímpar.

numero=int(input("Digite um número: "))
if numero%2==0:
    print("O número", numero, "é par.")
else:
    print("O número", numero, "é ímpar.")
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")